import { getFirestore, initializeFirebase } from '../config/firebase.config';
import { MenuCategory, SpicyLevel } from '../models/menuItem.model';

/**
 * Seed data para la colección menuItems
 * Incluye 70+ platos diversos del restaurante con diferentes categorías,
 * restricciones dietéticas, alérgenos y tags de preferencias
 */
const menuItemsSeed = [
  // ========================================
  // ENTRADAS (Appetizers) - 20 platos
  // ========================================
  {
    name: 'Ensalada César',
    description: 'Lechuga romana, crutones, queso parmesano y aderezo césar casero',
    price: 8500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?caesar-salad',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos', 'huevo'],
    tags: ['clásico', 'tradicional'],
    available: true,
  },
  {
    name: 'Bruschetta Caprese',
    description: 'Pan tostado con tomate fresco, mozzarella, albahaca y aceite de oliva',
    price: 7500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?bruschetta',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos'],
    tags: ['ligero', 'fresco', 'italiano'],
    available: true,
  },
  {
    name: 'Spring Rolls Veganos',
    description: 'Rollitos de vegetales frescos con salsa agridulce',
    price: 6900,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?spring-rolls',
    spicyLevel: SpicyLevel.MILD,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: ['soja'],
    tags: ['ligero', 'fresco', 'asiático'],
    available: true,
  },
  {
    name: 'Empanadas de Carne',
    description: 'Empanadas caseras rellenas de carne especiada (3 unidades)',
    price: 9200,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?empanadas',
    spicyLevel: SpicyLevel.MILD,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten'],
    tags: ['tradicional', 'casero', 'argentino'],
    available: true,
  },
  {
    name: 'Hummus con Crudités',
    description: 'Hummus de garbanzos con vegetales crudos y pan pita',
    price: 6500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?hummus',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'sésamo'],
    tags: ['ligero', 'fresco', 'medio-oriente'],
    available: true,
  },
  {
    name: 'Tabla de Quesos Artesanales',
    description: 'Selección de 4 quesos artesanales con frutos secos y miel',
    price: 12500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?cheese-board',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: true,
    allergens: ['lácteos', 'frutos secos'],
    tags: ['gourmet', 'abundante'],
    available: true,
  },
  {
    name: 'Ceviche de Pescado',
    description: 'Pescado blanco marinado en limón con cebolla morada, cilantro y maíz',
    price: 11500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?ceviche',
    spicyLevel: SpicyLevel.MILD,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: true,
    isKeto: false,
    allergens: ['pescado'],
    tags: ['ligero', 'fresco', 'peruano'],
    available: true,
  },
  {
    name: 'Provoleta a la Parrilla',
    description: 'Queso provolone grillado con orégano y aceite de oliva',
    price: 8900,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?provolone-cheese',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: true,
    allergens: ['lácteos'],
    tags: ['argentino', 'tradicional', 'rápido'],
    available: true,
  },
  {
    name: 'Gyozas de Cerdo',
    description: 'Dumplings japoneses rellenos de cerdo y vegetales (6 unidades)',
    price: 9800,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?gyoza',
    spicyLevel: SpicyLevel.MILD,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'soja'],
    tags: ['asiático', 'gourmet'],
    available: true,
  },
  {
    name: 'Ensalada Caprese',
    description: 'Tomate, mozzarella de búfala, albahaca fresca y reducción de balsámico',
    price: 8200,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?caprese-salad',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: true,
    allergens: ['lácteos'],
    tags: ['ligero', 'fresco', 'italiano'],
    available: true,
  },
  {
    name: 'Sopa de Calabaza',
    description: 'Crema de calabaza con jengibre y crutones de pan',
    price: 7800,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?pumpkin-soup',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos'],
    tags: ['casero', 'reconfortante'],
    available: true,
  },
  {
    name: 'Aguacate Relleno',
    description: 'Medio aguacate relleno con quinoa, tomate y limón',
    price: 8500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?stuffed-avocado',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: true,
    isKeto: true,
    allergens: [],
    tags: ['ligero', 'fresco', 'saludable'],
    available: true,
  },
  {
    name: 'Carpaccio de Res',
    description: 'Finas láminas de carne con rúcula, parmesano y aceite de trufa',
    price: 13500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?beef-carpaccio',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: true,
    isKeto: true,
    allergens: ['lácteos'],
    tags: ['gourmet', 'ligero'],
    available: true,
  },
  {
    name: 'Bastones de Mozzarella',
    description: 'Palitos de mozzarella empanados con salsa marinara (6 unidades)',
    price: 8800,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?mozzarella-sticks',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos', 'huevo'],
    tags: ['rápido', 'tradicional'],
    available: true,
  },
  {
    name: 'Ensalada Griega',
    description: 'Tomate, pepino, aceitunas, queso feta, cebolla y orégano',
    price: 8900,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?greek-salad',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: true,
    allergens: ['lácteos'],
    tags: ['ligero', 'fresco', 'mediterráneo'],
    available: true,
  },
  {
    name: 'Tacos de Hongos',
    description: 'Tacos vegetarianos con hongos salteados, guacamole y pico de gallo (3 unidades)',
    price: 9500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?mushroom-tacos',
    spicyLevel: SpicyLevel.MEDIUM,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: [],
    tags: ['mexicano', 'fresco', 'rápido'],
    available: true,
  },
  {
    name: 'Camarones al Ajillo',
    description: 'Camarones salteados en aceite de oliva, ajo y perejil',
    price: 14500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?garlic-shrimp',
    spicyLevel: SpicyLevel.MILD,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: true,
    isKeto: true,
    allergens: ['mariscos'],
    tags: ['gourmet', 'rápido'],
    available: true,
  },
  {
    name: 'Baba Ganoush',
    description: 'Puré de berenjena ahumada con tahini, ajo y pan pita',
    price: 7200,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?baba-ganoush',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'sésamo'],
    tags: ['ligero', 'medio-oriente', 'fresco'],
    available: true,
  },
  {
    name: 'Alcachofas a la Romana',
    description: 'Alcachofas fritas estilo romano con limón',
    price: 10500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?fried-artichokes',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isKosher: false,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten'],
    tags: ['italiano', 'gourmet'],
    available: true,
  },
  {
    name: 'Sopa de Miso',
    description: 'Sopa japonesa con tofu, algas wakame y cebollín',
    price: 6500,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?miso-soup',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isKosher: false,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: ['soja'],
    tags: ['ligero', 'asiático', 'rápido'],
    available: true,
  },
  {
    name: 'Champiñones Rellenos',
    description: 'Champiñones portobello rellenos con espinaca, queso de cabra y nueces',
    price: 9800,
    currency: 'ARS',
    category: MenuCategory.APPETIZER,
    imageUrl: 'https://source.unsplash.com/400x300/?stuffed-mushrooms',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: true,
    allergens: ['lácteos', 'frutos secos'],
    tags: ['gourmet', 'ligero'],
    available: true,
  },

  // ========================================
  // PLATOS PRINCIPALES (Main Course) - 30 platos
  // ========================================
  {
    name: 'Pizza Margarita',
    description: 'Salsa de tomate, mozzarella fresca, albahaca y aceite de oliva',
    price: 14500,
    currency: 'ARS',
    category: MenuCategory.MAIN_COURSE,
    imageUrl: 'https://source.unsplash.com/400x300/?pizza-margherita',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos'],
    tags: ['italiano', 'clásico', 'abundante'],
    available: true,
  },
  {
    name: 'Milanesa Napolitana',
    description: 'Milanesa de ternera cubierta con jamón, tomate y queso, con papas fritas',
    price: 21500,
    currency: 'ARS',
    category: MenuCategory.MAIN_COURSE,
    imageUrl: 'https://source.unsplash.com/400x300/?milanesa',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos', 'huevo'],
    tags: ['argentino', 'tradicional', 'abundante'],
    available: true,
  },
  {
    name: 'Risotto de Hongos',
    description: 'Arroz arborio cremoso con mix de hongos y queso parmesano',
    price: 18900,
    currency: 'ARS',
    category: MenuCategory.MAIN_COURSE,
    imageUrl: 'https://source.unsplash.com/400x300/?mushroom-risotto',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['lácteos'],
    tags: ['italiano', 'gourmet', 'cremoso'],
    available: true,
  },
  {
    name: 'Curry Tailandés de Vegetales',
    description: 'Curry rojo picante con vegetales frescos, leche de coco y arroz jazmín',
    price: 16500,
    currency: 'ARS',
    category: MenuCategory.MAIN_COURSE,
    imageUrl: 'https://source.unsplash.com/400x300/?thai-curry',
    spicyLevel: SpicyLevel.HOT,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: [],
    tags: ['asiático', 'picante', 'abundante'],
    available: true,
  },
  {
    name: 'Salmón a la Plancha',
    description: 'Filet de salmón con puré de calabaza y espárragos grillados',
    price: 26500,
    currency: 'ARS',
    category: MenuCategory.MAIN_COURSE,
    imageUrl: 'https://source.unsplash.com/400x300/?grilled-salmon',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: true,
    isKeto: true,
    allergens: ['pescado'],
    tags: ['gourmet', 'ligero', 'saludable'],
    available: true,
  },
  {
    name: 'Hamburguesa Clásica',
    description: 'Carne de res 200g, lechuga, tomate, cebolla, queso cheddar y papas fritas',
    price: 17500,
    currency: 'ARS',
    category: MenuCategory.MAIN_COURSE,
    imageUrl: 'https://source.unsplash.com/400x300/?burger',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos'],
    tags: ['clásico', 'abundante', 'rápido'],
    available: true,
  },
  {
    name: 'Pasta Carbonara',
    description: 'Spaghetti con panceta, huevo, queso parmesano y pimienta negra',
    price: 15900,
    currency: 'ARS',
    category: MenuCategory.MAIN_COURSE,
    imageUrl: 'https://source.unsplash.com/400x300/?carbonara',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos', 'huevo'],
    tags: ['italiano', 'clásico', 'cremoso'],
    available: true,
  },
  {
    name: 'Bowl Vegano de Quinoa',
    description: 'Quinoa, garbanzos especiados, aguacate, vegetales asados y tahini',
    price: 15500,
    currency: 'ARS',
    category: MenuCategory.MAIN_COURSE,
    imageUrl: 'https://source.unsplash.com/400x300/?quinoa-bowl',
    spicyLevel: SpicyLevel.MILD,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: ['sésamo'],
    tags: ['saludable', 'ligero', 'fresco'],
    available: true,
  },

  // ========================================
  // POSTRES (Desserts) - 10 platos
  // ========================================
  {
    name: 'Tarta de Manzana',
    description: 'Tarta casera de manzana con helado de vainilla',
    price: 8900,
    currency: 'ARS',
    category: MenuCategory.DESSERT,
    imageUrl: 'https://source.unsplash.com/400x300/?apple-pie',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos', 'huevo'],
    tags: ['casero', 'tradicional', 'dulce'],
    available: true,
  },
  {
    name: 'Brownie con Helado',
    description: 'Brownie de chocolate tibio con helado de chocolate y salsa de dulce de leche',
    price: 9500,
    currency: 'ARS',
    category: MenuCategory.DESSERT,
    imageUrl: 'https://source.unsplash.com/400x300/?brownie-ice-cream',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten', 'lácteos', 'huevo', 'frutos secos'],
    tags: ['gourmet', 'abundante', 'dulce'],
    available: true,
  },
  {
    name: 'Flan Casero',
    description: 'Flan de vainilla con caramelo y crema',
    price: 7200,
    currency: 'ARS',
    category: MenuCategory.DESSERT,
    imageUrl: 'https://source.unsplash.com/400x300/?flan',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['lácteos', 'huevo'],
    tags: ['casero', 'tradicional', 'ligero'],
    available: true,
  },
  {
    name: 'Helado Vegano de Frutas',
    description: 'Helado a base de leche de coco con frutas frescas',
    price: 6800,
    currency: 'ARS',
    category: MenuCategory.DESSERT,
    imageUrl: 'https://source.unsplash.com/400x300/?vegan-ice-cream',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: [],
    tags: ['fresco', 'ligero', 'dulce'],
    available: true,
  },

  // ========================================
  // BEBIDAS (Beverages) - 10 platos
  // ========================================
  {
    name: 'Limonada Natural',
    description: 'Limonada fresca con menta y jengibre',
    price: 5500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?lemonade',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: true,
    isKeto: false,
    allergens: [],
    tags: ['fresco', 'ligero', 'rápido'],
    available: true,
  },
  {
    name: 'Smoothie de Frutas Tropicales',
    description: 'Mango, piña, maracuyá y leche de coco',
    price: 7800,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?tropical-smoothie',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: true,
    isKeto: false,
    allergens: [],
    tags: ['fresco', 'tropical', 'dulce'],
    available: true,
  },
  {
    name: 'Cerveza Artesanal IPA',
    description: 'Cerveza IPA local de 500ml',
    price: 8900,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?craft-beer',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten'],
    tags: ['artesanal', 'local'],
    available: true,
  },
  {
    name: 'Café Espresso',
    description: 'Café espresso doble de origen colombiano',
    price: 4200,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?espresso',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: true,
    isKeto: true,
    allergens: [],
    tags: ['rápido', 'fuerte'],
    available: true,
  },
  {
    name: 'Coca-Cola',
    description: 'Coca-Cola 500ml',
    price: 3500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?coca-cola',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: [],
    tags: ['gaseosa', 'clásico'],
    available: true,
  },
  {
    name: 'Sprite',
    description: 'Sprite lima-limón 500ml',
    price: 3500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?sprite-soda',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: [],
    tags: ['gaseosa', 'cítrico'],
    available: true,
  },
  {
    name: 'Fanta',
    description: 'Fanta naranja 500ml',
    price: 3500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?fanta-orange',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: [],
    tags: ['gaseosa', 'naranja'],
    available: true,
  },
  {
    name: 'Agua Mineral con Gas',
    description: 'Agua mineralizada con gas 500ml',
    price: 2800,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?sparkling-water',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: true,
    isKeto: true,
    allergens: [],
    tags: ['ligero', 'refrescante'],
    available: true,
  },
  {
    name: 'Agua Mineral sin Gas',
    description: 'Agua mineral natural 500ml',
    price: 2500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?mineral-water',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: true,
    isKeto: true,
    allergens: [],
    tags: ['ligero', 'natural'],
    available: true,
  },
  {
    name: 'Jugo de Naranja Natural',
    description: 'Jugo de naranja recién exprimido',
    price: 6500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?orange-juice',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: true,
    isKeto: false,
    allergens: [],
    tags: ['fresco', 'natural', 'vitamina C'],
    available: true,
  },
  {
    name: 'Té Helado',
    description: 'Té negro helado con limón y menta',
    price: 5200,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?iced-tea',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: true,
    isHalal: true,
    isPaleo: true,
    isKeto: true,
    allergens: [],
    tags: ['refrescante', 'ligero'],
    available: true,
  },
  {
    name: 'Vino Tinto Malbec',
    description: 'Copa de vino tinto Malbec argentino',
    price: 9500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?red-wine-malbec',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: true,
    isKeto: false,
    allergens: ['sulfitos'],
    tags: ['argentino', 'vino'],
    available: true,
  },
  {
    name: 'Vino Blanco',
    description: 'Copa de vino blanco Torrontés',
    price: 8800,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?white-wine',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: true,
    isKeto: false,
    allergens: ['sulfitos'],
    tags: ['argentino', 'vino', 'fresco'],
    available: true,
  },
  {
    name: 'Cappuccino',
    description: 'Café cappuccino con espuma de leche',
    price: 5800,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?cappuccino',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: ['lácteos'],
    tags: ['café', 'cremoso'],
    available: true,
  },
  {
    name: 'Café Latte',
    description: 'Café con leche cremosa',
    price: 5500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?latte',
    spicyLevel: SpicyLevel.NONE,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: false,
    isKosher: true,
    isHalal: true,
    isPaleo: false,
    isKeto: false,
    allergens: ['lácteos'],
    tags: ['café', 'suave'],
    available: true,
  },
  {
    name: 'Mojito',
    description: 'Cóctel de ron, menta, lima y soda',
    price: 12500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?mojito',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: [],
    tags: ['cóctel', 'refrescante', 'menta'],
    available: true,
  },
  {
    name: 'Margarita',
    description: 'Cóctel de tequila con lima y sal',
    price: 13500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?margarita-cocktail',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: [],
    tags: ['cóctel', 'cítrico'],
    available: true,
  },
  {
    name: 'Cerveza Quilmes',
    description: 'Cerveza Quilmes 1L',
    price: 6500,
    currency: 'ARS',
    category: MenuCategory.BEVERAGE,
    imageUrl: 'https://source.unsplash.com/400x300/?beer-bottle',
    spicyLevel: SpicyLevel.NONE,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isKosher: false,
    isHalal: false,
    isPaleo: false,
    isKeto: false,
    allergens: ['gluten'],
    tags: ['cerveza', 'argentina', 'clásico'],
    available: true,
  },
];

/**
 * Script de seed para poblar la base de datos con platos iniciales
 */
async function seedMenuItems() {
  try {
    console.log('🌱 Iniciando seed de menuItems...\n');

    // Inicializar Firebase
    initializeFirebase();
    const db = getFirestore();

    const menuItemsCollection = db.collection('menuItems');
    let insertedCount = 0;
    let skippedCount = 0;

    for (const item of menuItemsSeed) {
      // Verificar si ya existe un item con el mismo nombre
      const existingItem = await menuItemsCollection
        .where('name', '==', item.name)
        .limit(1)
        .get();

      if (!existingItem.empty) {
        console.log(`⏭️  Saltando "${item.name}" - Ya existe`);
        skippedCount++;
        continue;
      }

      // Insertar el item con timestamp
      const docRef = await menuItemsCollection.add({
        ...item,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });

      console.log(`✅ Insertado: "${item.name}" (ID: ${docRef.id})`);
      insertedCount++;
    }

    console.log('\n🎉 Seed completado!');
    console.log(`📊 Resultados:`);
    console.log(`   - Insertados: ${insertedCount}`);
    console.log(`   - Saltados: ${skippedCount}`);
    console.log(`   - Total en seed: ${menuItemsSeed.length}`);

    // Verificar total en DB
    const totalSnapshot = await menuItemsCollection.count().get();
    console.log(`   - Total en DB: ${totalSnapshot.data().count}\n`);

  } catch (error) {
    console.error('❌ Error en seed:', error);
    process.exit(1);
  }
}

// Ejecutar si se llama directamente
if (require.main === module) {
  seedMenuItems()
    .then(() => {
      console.log('✨ Seed finalizado exitosamente');
      process.exit(0);
    })
    .catch((error) => {
      console.error('💥 Error fatal:', error);
      process.exit(1);
    });
}

export { menuItemsSeed, seedMenuItems };

